services:
  #---------------Backend--------------------
  backend:
    build:
      context: ../members-only-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../members-only-backend/src:/app/src
      - ../members-only-backend/prisma:/app/prisma
    env_file:
      - ../members-only-backend/.env
    networks:
      - members-only

  #---------------Frontend--------------------
  frontend:
    build:
      context: ../members-only-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../members-only-frontend/src:/app/src
    env_file:
      - ../members-only-frontend/.env.development
    networks:
      - members-only

#---------------Network--------------------
networks:
  members-only:
    driver: bridge
